highlight Normal guibg=grey90
highlight Cursor guibg=green guifg=NONE
highlight NonText guibg=grey80
highlight Constant guibg=grey90
highlight Special gui=NONE guibg=grey90
highlight StatusLine gui=bold guifg=white guibg=blue
set guifont=DejaVu\ Sans\ Mono\ 12
colorscheme onedark
set guioptions=egmrt
highlight SignColumn guibg=black guifg=black
highlight GitGutterAdd guibg=black guifg=green
highlight GitGutterChange guibg=black guifg=yellow
highlight GitGutterDelete guibg=black guifg=red
highlight GitGutterChangeDelete guibg=black guifg=magenta
